#
# Makefile for misc devices that really don't fit anywhere else.
#
ldflags-y := -flto

obj-y += nt36672D_fhdp_dsi_vdo_dijing_j19.o

ccflags-$(CONFIG_MTK_LCM) +=  -I$(srctree)/drivers/misc/mediatek/lcm/inc
